-- MySQL Script generated by MySQL Workbench
-- Thu Mar 20 23:55:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clinic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinic` ;

-- -----------------------------------------------------
-- Schema clinic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinic` DEFAULT CHARACTER SET utf8mb3 ;
USE `clinic` ;

-- -----------------------------------------------------
-- Table `clinic`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`patients` ;

CREATE TABLE IF NOT EXISTS `clinic`.`patients` (
  `mrn` VARCHAR(15) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `sex` ENUM('M', 'F') NOT NULL,
  `birth_date` DATE NOT NULL,
  `contact_no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`mrn`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`doctors` ;

CREATE TABLE IF NOT EXISTS `clinic`.`doctors` (
  `npi` VARCHAR(15) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `First_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `sex` ENUM('M', 'F') NOT NULL,
  `birth_date` DATE NOT NULL,
  `medical_certification` VARCHAR(45) NOT NULL,
  `years_of_service` INT NOT NULL,
  `specialization` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`npi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`lab_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`lab_requests` ;

CREATE TABLE IF NOT EXISTS `clinic`.`lab_requests` (
  `lab_request_id` VARCHAR(15) NOT NULL,
  `npi` VARCHAR(15) NOT NULL,
  `mrn` VARCHAR(15) NOT NULL,
  `reason` VARCHAR(45) NOT NULL,
  `request_date` DATE NOT NULL,
  PRIMARY KEY (`lab_request_id`),
  INDEX `idx_doctors_npi` (`npi` ASC) VISIBLE,
  INDEX `idx_patients_mrn` (`mrn` ASC) VISIBLE,
  CONSTRAINT `fk_lab_requests_mrn`
    FOREIGN KEY (`mrn`)
    REFERENCES `clinic`.`patients` (`mrn`),
  CONSTRAINT `fk_lab_requests_npi`
    FOREIGN KEY (`npi`)
    REFERENCES `clinic`.`doctors` (`npi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`payments` ;

CREATE TABLE IF NOT EXISTS `clinic`.`payments` (
  `payment_id` VARCHAR(15) NOT NULL,
  `lab_report_id` VARCHAR(15) NOT NULL,
  `mrn` VARCHAR(15) NOT NULL,
  `appointment_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `idx_appointments_appointment_id` (`appointment_id` ASC) INVISIBLE,
  INDEX `idx_lab_reports_lab_report_id` (`lab_report_id` ASC) VISIBLE,
  INDEX `idx_patients_mrn` (`mrn` ASC) VISIBLE,
  CONSTRAINT `fk_payments_appointment_id`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `clinic`.`appointments` (`appointment_id`),
  CONSTRAINT `fk_payments_lab_report_id`
    FOREIGN KEY (`lab_report_id`)
    REFERENCES `clinic`.`lab_reports` (`lab_report_id`),
  CONSTRAINT `fk_payments_mrn`
    FOREIGN KEY (`mrn`)
    REFERENCES `clinic`.`patients` (`mrn`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`lab_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`lab_reports` ;

CREATE TABLE IF NOT EXISTS `clinic`.`lab_reports` (
  `lab_report_id` VARCHAR(15) NOT NULL,
  `lab_request_id` VARCHAR(15) NOT NULL,
  `mrn` VARCHAR(15) NOT NULL,
  `npi` VARCHAR(15) NOT NULL,
  `payment_id` VARCHAR(15) NULL DEFAULT NULL,
  `findings` VARCHAR(45) NOT NULL,
  `lab_test_datetime` DATETIME NOT NULL,
  `lab_fees` DOUBLE NOT NULL,
  `lab_results` VARCHAR(45) NULL DEFAULT NULL,
  `report_status` ENUM('pending', 'completed') NOT NULL,
  PRIMARY KEY (`lab_report_id`),
  INDEX `idx_doctors_npi` (`npi` ASC) VISIBLE,
  INDEX `idx_patients_mrn` (`mrn` ASC) VISIBLE,
  INDEX `idx_lab_reports_lab_report_id` (`lab_report_id` ASC) INVISIBLE,
  INDEX `idx_payments_payment_id` (`payment_id` ASC) VISIBLE,
  INDEX `fk_lab_reports_lab_request_id` (`lab_request_id` ASC) VISIBLE,
  CONSTRAINT `fk_lab_reports_lab_request_id`
    FOREIGN KEY (`lab_request_id`)
    REFERENCES `clinic`.`lab_requests` (`lab_request_id`),
  CONSTRAINT `fk_lab_reports_mrn`
    FOREIGN KEY (`mrn`)
    REFERENCES `clinic`.`patients` (`mrn`),
  CONSTRAINT `fk_lab_reports_npi`
    FOREIGN KEY (`npi`)
    REFERENCES `clinic`.`doctors` (`npi`),
  CONSTRAINT `fk_lab_reports_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `clinic`.`payments` (`payment_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`appointments` ;

CREATE TABLE IF NOT EXISTS `clinic`.`appointments` (
  `appointment_id` VARCHAR(15) NOT NULL,
  `mrn` VARCHAR(15) NOT NULL,
  `npi` VARCHAR(15) NOT NULL,
  `lab_report_id` VARCHAR(15) NOT NULL,
  `purpose` VARCHAR(45) NULL DEFAULT NULL,
  `start_datetime` DATETIME NULL DEFAULT NULL,
  `end_datetime` DATETIME NULL DEFAULT NULL,
  `total_fees` DOUBLE NULL DEFAULT NULL,
  `payment_status` ENUM('unpaid', 'paid', 'refunded') NULL DEFAULT NULL,
  PRIMARY KEY (`appointment_id`),
  UNIQUE INDEX `idx_appointments_appointment_id` (`appointment_id` ASC) VISIBLE,
  INDEX `idx_doctors_npi` (`npi` ASC) VISIBLE,
  INDEX `idx_patients_mrn` (`mrn` ASC) VISIBLE,
  INDEX `idx_lab_reports_lab_report_id` (`lab_report_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_lab_report_id`
    FOREIGN KEY (`lab_report_id`)
    REFERENCES `clinic`.`lab_reports` (`lab_report_id`),
  CONSTRAINT `fk_appointments_mrn`
    FOREIGN KEY (`mrn`)
    REFERENCES `clinic`.`patients` (`mrn`),
  CONSTRAINT `fk_appointments_npi`
    FOREIGN KEY (`npi`)
    REFERENCES `clinic`.`doctors` (`npi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`bookings` ;

CREATE TABLE IF NOT EXISTS `clinic`.`bookings` (
  `booking` VARCHAR(15) NOT NULL,
  `appointment_id` VARCHAR(15) NOT NULL,
  `mrn` VARCHAR(15) NOT NULL,
  `npi` VARCHAR(15) NOT NULL,
  `booking_date` DATE NOT NULL,
  `appointment_date` DATETIME NOT NULL,
  PRIMARY KEY (`booking`),
  INDEX `idx_doctors_npi` (`npi` ASC) VISIBLE,
  INDEX `idx_patients_mrn` (`mrn` ASC) VISIBLE,
  INDEX `idx_appointments_appointment_id` (`appointment_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_appointment_d`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `clinic`.`appointments` (`appointment_id`),
  CONSTRAINT `fk_bookings_mrn`
    FOREIGN KEY (`mrn`)
    REFERENCES `clinic`.`patients` (`mrn`),
  CONSTRAINT `fk_bookings_npi`
    FOREIGN KEY (`npi`)
    REFERENCES `clinic`.`doctors` (`npi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`diagnosis` ;

CREATE TABLE IF NOT EXISTS `clinic`.`diagnosis` (
  `diagnosis_id` VARCHAR(15) NOT NULL,
  `lab_report_id` VARCHAR(15) NOT NULL,
  `diagnosis` VARCHAR(45) NOT NULL,
  `treatment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`diagnosis_id`),
  INDEX `idx_lab_reports_lab_report_id` (`lab_report_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosis_lab_report_id`
    FOREIGN KEY (`lab_report_id`)
    REFERENCES `clinic`.`lab_reports` (`lab_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinic`.`prescriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinic`.`prescriptions` ;

CREATE TABLE IF NOT EXISTS `clinic`.`prescriptions` (
  `prescription_id` VARCHAR(15) NOT NULL,
  `mrn` VARCHAR(15) NOT NULL,
  `npi` VARCHAR(15) NOT NULL,
  `medication_name` VARCHAR(45) NOT NULL,
  `dosage` DOUBLE NOT NULL,
  `frequency` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prescription_id`),
  INDEX `idx_doctors_npi` (`npi` ASC) INVISIBLE,
  INDEX `idx_patients_mrn` (`mrn` ASC) VISIBLE,
  CONSTRAINT `fk_prescriptions_mrn`
    FOREIGN KEY (`mrn`)
    REFERENCES `clinic`.`patients` (`mrn`),
  CONSTRAINT `fk_prescriptions_npi`
    FOREIGN KEY (`npi`)
    REFERENCES `clinic`.`doctors` (`npi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
