# Global logging level
.level = INFO

# Console handler configuration
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# File handler configuration
java.util.logging.FileHandler.level = ALL
java.util.logging.FileHandler.pattern = C:\Users\Akaraan\Documents\GitHub\INFOMM\clinicdb\src
java.util.logging.FileHandler.limit = 50000  # Maximum size of the log file (50 KB)
java.util.logging.FileHandler.count = 1       # Number of log files to keep (1 means only the current log file)
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter

# Optional: Set the file handler to append to the log file instead of overwriting it
java.util.logging.FileHandler.append = true